name: Предложить улучшение
description: Новая функция или улучшение интерфейса
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: usecase
    attributes:
      label: Какую задачу нужно решить?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Предлагаемое решение
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Рассмотренные альтернативы
